DROP TABLE IF EXISTS CF_classify;
CREATE TABLE CF_classify (
	classifyId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	classifyName_m VARCHAR(20) NOT NULL,
	classifyClass_x VARCHAR(50) NOT NULL,
	seq_c INT NOT NULL,
	status_x VARCHAR(10) NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	updOn_dt DATETIME NULL,
	updBy_m VARCHAR(20) NULL,
	PRIMARY KEY (classifyId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_category;
CREATE TABLE CF_category (
		categoryId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
		categoryName_m VARCHAR(20) NOT NULL,
		path_x VARCHAR(50) NOT NULL,
		classifyId_n INT UNSIGNED NOT NULL,
		seq_c INT NOT NULL,
		active_c CHAR(1) NOT NULL,
		crtOn_dt DATETIME NOT NULL,
		crtBy_m VARCHAR(20) NOT NULL,
		updOn_dt DATETIME NULL,
		updBy_m VARCHAR(20) NULL,
		PRIMARY KEY (categoryId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_record;
CREATE TABLE CF_record (
		recordId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
		type_x VARCHAR(10) NOT NULL,
		late_c CHAR(1) NOT NULL,
		count_n INT NULL,
		weight_n DOUBLE NULL,
		price_n DOUBLE NULL,
		amount_n DOUBLE NULL,
		desc_x VARCHAR(200) NULL,
		record_dt DATETIME NOT NULL,
		active_c CHAR(1) NOT NULL,		
		crtBy_m VARCHAR(20) NOT NULL,
		crtOn_dt DATETIME NOT NULL,
		PRIMARY KEY (recordId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_attachment;
CREATE TABLE CF_attachment (
	attachId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	categoryId_n INT UNSIGNED NOT NULL,
	path_x VARCHAR(200) NOT NULL,
	attachName_m VARCHAR(20) NOT NULL,
	month_x VARCHAR(10) NOT NULL,
	active_c CHAR(1) NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY (attachId_n)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS CF_memo;
CREATE TABLE CF_memo (
	memoId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	userId_n INT UNSIGNED NOT NULL,
	content_x VARCHAR(200) NOT NULL,
	day_d DATE NOT NULL,
	status_x VARCHAR(10) NOT NULL,
	active_c CHAR(1) NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY (memoId_n)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS CF_image;
CREATE TABLE CF_image (
	imageId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	userId_n INT UNSIGNED NOT NULL,
	name_m VARCHAR(100) NOT NULL,
	path_x VARCHAR(200) NOT NULL,
	active_c CHAR(1) NOT NULL,
	remove_dt DATETIME NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY (imageId_n)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS CF_alert;
CREATE TABLE CF_alert (
	alertId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	method_x VARCHAR(5) NOT NULL,
	phone_x VARCHAR(15) NULL,
	email_x VARCHAR(200) NULL,
	status_x VARCHAR(10) NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY (alertId_n)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS CF_code;
CREATE TABLE CF_code (
	codeId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	type_x VARCHAR(20) NOT NULL,
	name_x VARCHAR(50) NOT NULL,
	value_x VARCHAR(50) NOT NULL,
	desc_x VARCHAR(200) NULL,
	active_c CHAR(1) NOT NULL DEFAULT 'A',
	crtBy_m VARCHAR(20) NOT NULL DEFAULT 'System',
	crtOn_dt DATETIME NOT NULL DEFAULT NOW(),
	PRIMARY KEY (codeId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_user;
CREATE TABLE CF_user (
	userId_n INT NOT NULL AUTO_INCREMENT,
	username_m VARCHAR(20) NOT NULL,
	password_x VARCHAR(64) NOT NULL,
	enabled_c CHAR NOT NULL DEFAULT 'Y',
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	updOn_dt DATETIME NULL,
	updBy_m VARCHAR(20) NULL,
	PRIMARY KEY(userId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_userInfo;
CREATE TABLE CF_userInfo (
	infoId_n INT UNSIGNED AUTO_INCREMENT NOT NULL,
	userId_n INT NOT NULL,
	name_m VARCHAR(20) NOT NULL,
	sex_c CHAR(1) NOT NULL,
	age_n INT NOT NULL,
	fromPlace_m VARCHAR(20) NOT NULL,
	birth_d DATETIME NOT NULL,
	school_m VARCHAR(50) NULL,
	phone_x VARCHAR(11) NOT NULL,
	email_x VARCHAR(200) NOT NULL,
	weight_n DOUBLE NULL,
	height_n DOUBLE NULL,
	intro_x VARCHAR(200) NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	updOn_dt DATETIME NULL,
	updBy_m VARCHAR(20) NULL,
	PRIMARY KEY (infoId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_role;
CREATE TABLE CF_role (
	roleId_n INT AUTO_INCREMENT NOT NULL,
	roleName_m VARCHAR(20) NOT NULL,
	enabled_c CHAR NOT NULL DEFAULT 'Y',
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(roleId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_resource;
CREATE TABLE CF_resource (
	resId_n INT AUTO_INCREMENT NOT NULL,
	resType_x VARCHAR(20) NOT NULL,
	resPath_x VARCHAR(20) NOT NULL,
	resDesc_x VARCHAR(50) NULL,
	enabled_c CHAR NOT NULL DEFAULT 'Y',
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(resId_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_user2role;
CREATE TABLE CF_user2role (
	id_n INT AUTO_INCREMENT NOT NULL,
	userId_n INT NOT NULL,
	roleId_n INT NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(id_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_role2res;
CREATE TABLE CF_role2res (
	id_n INT AUTO_INCREMENT NOT NULL,
	roleId_n INT NOT NULL,
	resId_n INT NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	crtBy_m VARCHAR(20) NOT NULL,
	PRIMARY KEY(id_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS CF_loginHistory;
CREATE TABLE CF_loginHistory (
	id_n INT AUTO_INCREMENT NOT NULL,
	username_m VARCHAR(20) NOT NULL,
	ip_x VARCHAR(20) NOT NULL,
	status_x VARCHAR(10) NOT NULL,
	crtOn_dt DATETIME NOT NULL,
	PRIMARY KEY(id_n)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;